name: Java CI with Maven
'on':
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 11
        uses: actions/setup-java@v4.6.0
        with:
          distribution: jdk
      - name: Build with Maven
        run: mvn -B package --file pom.xml
